GET http://localhost:3000/api/videos

### Detalle numeroId
GET http://localhost:3000/api/videos/detalles/109

### Aleatorio
GET http://localhost:3000/api/videos/aleatorio

### Buscar
GET http://localhost:3000/api/videos/autor/mar

### Buscar general
GET http://localhost:3000/api/videos/buscar/playa
